apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "rbac-manager.fullname" . }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: {{ template "rbac-manager.name" . }}
    chart: {{ template "rbac-manager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
