# CSI Snapshotter

manifests:
  # VolumeSnapshotClass Config
  # See: https://kubernetes.io/docs/concepts/storage/volume-snapshot-classes/#the-volumesnapshotclass-resource
  vsclass:

    # Use v1 for K8s >= 1.20, v1beta1 for 1.17.x <= K8s < 1.20
    apiVersion: "v1"

    # VolumeSnapshotClass name
    name: "spectro-vsclass"

    # Whether or not the VolumeSnapshotClass is set as the default
    isDefaultClass: true

    # VolumeSnapshotClass driver, e.g., ebs.csi.aws.com for AWS EBS CSI driver
    # See: https://kubernetes-csi.github.io/docs/drivers.html#production-drivers
    driver: ""

    # VolumeSnapshotClass deletion policy. One of: [Delete, Retain]
    deletionPolicy: "Delete"

    # VolumeSnapshotClass parameters - variable based on CSI driver
    parameters:
      # Azure Disk
      # incremental: "true"

      # GCE Persistent Disk
      # storage-locations: us-east2