apiVersion: v1
kind: Service
metadata:
  labels:
{{- include "appdynamics-otel-collector.labels" . | nindent 4 }}
  name: {{ .Values.service.name }}
spec:
  selector:
    {{- include "appdynamics-otel-collector.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports: {{ include "appdynamics-otel-collector.servicePorts" . | nindent 4 }}