apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "validation-webhook.snapshot.storage.k8s.io"
  annotations:
    # auto-populates webhooks.clientConfig.caBundle
    cert-manager.io/inject-ca-from: kube-system/snapshot-validation-webhook-service-cert
webhooks:
- name: "validation-webhook.snapshot.storage.k8s.io"
  rules:
  - apiGroups:   ["snapshot.storage.k8s.io"]
    apiVersions: ["v1", "v1beta1"]
    operations:  ["CREATE", "UPDATE"]
    resources:   ["volumesnapshots", "volumesnapshotcontents"]
    scope:       "*"
  clientConfig:
    service:
      namespace: "kube-system"
      name: "snapshot-validation-service"
      path: "/volumesnapshot"
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  failurePolicy: Fail
  timeoutSeconds: 2 # This will affect the latency and performance. Finetune this value based on your application's tolerance.