pack:
  #The namespace the pack is installed
  namespace: "kubeflow-operator"

manifests:
  kubeflow-operator:
    registry: docker.io
    repository: aipipeline/kubeflow-operator
    tag: v1.2.0
  kubeflow-kfdef:
    contents: |
      apiVersion: kfdef.apps.kubeflow.org/v1
      kind: KfDef
      metadata:
        namespace: kubeflow-operator
        name: kubeflow
      spec:
        applications:
        - kustomizeConfig:
            repoRef:
              name: manifests
              path: namespaces/base
          name: namespaces
        - kustomizeConfig:
            repoRef:
              name: manifests
              path: application/v3
          name: application
        - kustomizeConfig:
            repoRef:
              name: manifests
              path: stacks/kubernetes/application/istio-1-3-1-stack
          name: istio-stack
        - kustomizeConfig:
            repoRef:
              name: manifests
              path: stacks/kubernetes/application/cluster-local-gateway-1-3-1
          name: cluster-local-gateway
        - kustomizeConfig:
            repoRef:
              name: manifests
              path: istio/istio/base
          name: istio
        - kustomizeConfig:
            repoRef:
              name: manifests
              path: stacks/kubernetes/application/add-anonymous-user-filter
          name: add-anonymous-user-filter
        - kustomizeConfig:
            repoRef:
              name: manifests
              path: metacontroller/base
          name: metacontroller
        - kustomizeConfig:
            repoRef:
              name: manifests
              path: admission-webhook/bootstrap/overlays/application
          name: bootstrap
        - kustomizeConfig:
            repoRef:
              name: manifests
              path: stacks/kubernetes/application/spark-operator
          name: spark-operator
        - kustomizeConfig:
            repoRef:
              name: manifests
              path: stacks/kubernetes
          name: kubeflow-apps
        - kustomizeConfig:
            repoRef:
              name: manifests
              path: knative/installs/generic
          name: knative
        - kustomizeConfig:
            repoRef:
              name: manifests
              path: kfserving/installs/generic
          name: kfserving
        repos:
        - name: manifests
          uri: https://github.com/kubeflow/manifests/archive/v1.2-branch.tar.gz
        version: v1.2-branch
