{{ if .Values.install.clustermon -}}
apiVersion: cluster.appdynamics.com/v1alpha1
kind: Clustermon
metadata:
  name: {{ printf "%s-%s" .Release.Name "appdynamics-clustermon" | trunc 63 }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- template "podConfigs" .Values.clustermonPod }}

  serviceAccountName: {{ .Values.clustermonServiceAccount}}

  {{ with .Values.global.tls.appdCollectors -}}
  mTLS:
    enabled: {{ .enabled | quote }}
    {{ if .enabled -}}
    secretName: {{ required "A valid secret name entry required!" .secret.secretName }}
    secretKeys:
      caCert: {{ .secret.secretKeys.caCert }}
      tlsCert: {{ .secret.secretKeys.tlsCert }}
      tlsKey: {{ .secret.secretKeys.tlsKey }}
    {{- end }}
  {{- end }}

  {{ with .Values.clustermonConfig -}}
  clusterName: {{ required "A valid clustermonConfig.clusterName entry required!" .clusterName }}
  logLevel: {{ .logLevel }}
  logFilesMaxSizeMb: {{ .logFilesMaxSizeMb }}
  logFilesNumBackups: {{ .logFilesNumBackups }}
  printToStdout: {{ .printToStdout | quote }}
  {{ if .gatherInterval -}}
  gatherInterval: {{ .gatherInterval }}
  {{- end }}

  filters:
    namespace:
    {{- toYaml .filters.namespace | nindent 6 }}
    entity:
    {{- toYaml .filters.entity | nindent 6 }}
    label:
    {{- toYaml .filters.label | nindent 6 }}

  {{ if .testSetupEnabled -}}
  testSetupEnabled: {{ .testSetupEnabled | quote }}
  {{- end }}
  {{ if .optimisedPayloadInterval -}}
  optimisedPayloadInterval: {{ .optimisedPayloadInterval }}
  {{- end }}
  {{ if .events -}}
  events:
    enabled: {{ .events.enabled | quote }}
    severityToExclude:
    {{- toYaml .events.severityToExclude | nindent 6 }}
    reasonToExclude:
    {{- toYaml .events.reasonToExclude | nindent 6 }}
    severeGroupByReason:
    {{- toYaml .events.severeGroupByReason | nindent 6 }}
  {{- end }}

  ingressControllers:
  {{- toYaml .ingressControllers | nindent 4 }}
  {{- end }}

  {{ with .Values.infraManagerConfig -}}
  infraManagerConfig:
    logFilesMaxSizeMb: {{ .logFilesMaxSizeMb }}
    logFilesNumBackups: {{ .logFilesNumBackups }}
    printToStdout: {{ .printToStdout | quote }}
    logLevel: {{ .logLevel }}
  {{- end }}

{{ end -}}
