{{ if .Values.install.defaultInfraCollectors -}}
apiVersion: cluster.appdynamics.com/v1alpha1
kind: Servermon
metadata:
  name: {{ printf "%s-%s" .Release.Name "appdynamics-servermon" | trunc 63 }}
  namespace: {{ .Release.Namespace }}
spec:
  {{ with .Values.servermonConfig -}}
  {{ if .gatherInterval -}}
  gatherInterval: {{ .gatherInterval }}
  {{- end }}
  logFilesMaxSizeMb: {{ .logFilesMaxSizeMb }}
  logFilesNumBackups: {{ .logFilesNumBackups }}
  logLevel: {{ .logLevel }}

  {{ if .skipProviderCheck -}}
  skipProviderCheck: {{ .skipProviderCheck | quote }}
  {{- end }}

  {{- end }}
{{- end }}