apiVersion: v2
appVersion: 22.6.0-9
dependencies:
- name: appdynamics-cloud-k8s-monitoring
  repository: ""
  version: 1.0.0
- name: appdynamics-otel-collector
  repository: ""
  version: 1.0.0
description: Helm Charts for installing Appdynamics Collectors
home: https://appdynamics.com
icon: https://raw.githubusercontent.com/CiscoDevNet/appdynamics-charts/master/logo.png
keywords:
- appdynamics
- cloud
- collector
- cluster
- kubernetes
- monitoring
- pod
- deployment
maintainers:
- email: support@appdynamics.com
  name: AppDynamics
name: appdynamics-collectors
type: application
version: 22.6.0-9
