global:
  tls:
    appdCollectors:
      enabled: false
      secret: {}
    otelReceiver:
      secret: {}
      settings: {}
    otelExporter:
      secret: {}
      settings: {}


appdynamics-cloud-k8s-monitoring:
  install:
    clustermon: true
    defaultInfraCollectors: true
    logCollector: false

  clustermonConfig:
    clusterName: ""

  clustermonPod:
    image: appdynamics/appdynamics-cloud-k8s-monitoring:22.6.0
    imagePullPolicy: Always
    imagePullSecrets: []

  inframonPod:
    image: appdynamics/appdynamics-cloud-k8s-monitoring:22.6.0
    imagePullPolicy: Always
    imagePullSecrets: []

  logCollectorPod:
    image: appdynamics/appdynamics-log-collector-agent:22.6.0
    imagePullPolicy: Always
    imagePullSecrets: []


appdynamics-otel-collector:
  spec:
    mode: daemonset # we set it to deployment in subchart, need to override it. The deployment setting is done on purpose.
    image: appdynamics/appdynamics-otel-collector:22.6.0
    imagePullPolicy: Always