manifests.install-falcon.agentPackageUrl:
  schema: '{{ required | format "${string}" | hints "Public URL to download the Falcon Sensor" }}'

manifests.install-falcon.customerId:
  schema: '{{ required | format "${password}" | hints "CustomerID to use for Falcon Sensor registration" }}'