pack:
  #The namespace (on the target cluster) to install this chart
  #When not found, a new namespace will be created
  namespace: "monitoring"

charts:
  # D:efault values for elasticsearch-curator.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

  cronjob:
    # Every 5 mins
    schedule: "*/5 * * * *"
    annotations: {}
    concurrencyPolicy: "Forbid"
    failedJobsHistoryLimit: "3"
    successfulJobsHistoryLimit: "1"

  customArguments: []

  pod:
    annotations: {}

  image:
    repository: aquasec/kube-hunter
    tag: 312
    pullPolicy: IfNotPresent

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
  #  cpu: 100m
  #  memory: 128Mi

  priorityClassName: ""
